version: "3.8"

services:
  # ****************************************************************************
  #
  #  Main Containers
  #
  # ****************************************************************************
  db:
    image: library/postgres:12-alpine
    container_name: locker_database
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=locker_dev
    ports:
      - 5432:5432

  # ****************************************************************************
  #
  #  Testing Containers
  #
  # **************************************************************************** 
  test_db:
    image: library/postgres:12-alpine
    container_name: locker_database
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5444
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=locker_dev_test
    ports:
      - 5444:5444
    command: -p 5444