name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Check linting
        run: npm run lint:check

      - name: Run tests
        env:
          NODE_ENV: test
          DB_URL: ${{ secrets.DB_URL_TEST }}
          LOCKER_API_KEY: fooBar
        run: npm run test
